### ISSUE TITLE
Additional input text 

### ISSUE THREAD

**Issue by mhoogenbosch** [AntoineGS/TeamsStatusV2#1]
With the introduction of the Camera status there is need for an additional input text field.

In readme.md:

```
This script makes use of two sensors that are created in Home Assistant up front:

sensor.teams_status
sensor.teams_activity
```

I've added the following:

```
input_text:
  teams_status:
    name: Microsoft Teams status
    icon: mdi:microsoft-teams
  teams_activity:
    name: Microsoft Teams activity
    icon: mdi:phone-off
  teams_cam_status:
    name: Microsoft Teams Camera Status
    icon: mdi:webcam
```
